WIPPS: tests Class Reference
tests Class Reference
Test code » Test framework
Test controller.
#include <tests.h>
Public Member Functions
void report_err (int err, int test_id=-1)
void report_info (std::string info, int verb_to_print=1)
void add_test (test_entity *test)
bool run_tests ()
void set_verbosity (size_t verb)
void set_runtime_flags (int argc, char *argv[])
void set_colour (char col=0)
bool check_for_abort (int err)
bool set_userdef_error (int err_code, std::string message)
Public Attributes
std::map< std::string, int > runtime_flags
Private Member Functions
std::string get_printable_error (int err, int test_id)
std::string get_colour_escape (char col)
bool is_fatal (int err)
void setup_tests ()
void cleanup_tests ()
void create_test_outdir ()
void clean_test_outdir (bool no_clean)
Private Attributes
std::fstream * outfile
int current_test_id
std::vector< test_entity * > test_list
int verbosity
bool no_clean = false
Detailed Description
Test controller.
Controls running of tests and their logging etc To add a test, do the following:
Descend an object from test_entity which has at least a constructor doing any setup required, a name string for output id, a function run taking no parameters which performs the necessary test and a destructor doing cleanup. Add any other member variables or functions required, including their headers also. In tests::setup_tests create an instance of your class as test_obj = new your_class() and then add your test to the remit using add_test(test_obj); Alternately make the instance and use the global test_bed using test_bed->add(your pntr) from anywhere.
To add errors, add the message into the blank spaces in the list below, err_names, and declare a const int of desired name aliased to TEST_USERDEF_ERR* where * = 1-4
To report the errors by code, call test_bed->report_err(err); To report other salient information use test_bed->report_info(info, verbosity) where the second parameter is an integer describing the verbosity setting at which to print this info (0 = always, larger means more and more detail. 1 is given as default parameter for this function).
Remember to also test whether things that "ought" to fail, do, and give suitable messages, cleanup etc.
To allow conditional running of tests etc, there is a map of runtime_flags which holds all command line arguments. These are assumed to be either a -flag_name or a pair -flag_name integer_flag_value. Available flags are:
In class test_entity_d:
Calculate a real diffusion coefficient for useful parameters, and check features against sample data Set runtime_flag "n" to a value to calculate a single n Set runtime_flag "d_pp" to calculate D_pp rather than alpha_alpha by default
In class test_entity_d:
A full useful calculation of a test coefficient takes quite a while, so here we just test that the calculation proceeds and there are no obvious problems. Set runtime_flag "full_d" to perform a full sample D calculation
In class test_entity_levelone:
Set runtime_flag "level_one" to perform full level-one testing
To include flags in these docs, include comment line in any functions in the relevant test_entity of the form "*Set runtime_flag "flag_name" to <action description>*" noting leading and trailing Doxy breaks (* with newline)
Todo:
Create test data for double-precision!
Definition at line 96 of file tests.h.
Member Function Documentation
void tests::add_test (test_entity * test)
Adds a test to the list to be performed
Parameters
test Pointer to test object to add. Object will be deleted on completion
Definition at line 90 of file tests.cpp.
Referenced by setup_tests().
bool tests::check_for_abort (int err)
Check for abort condition
Checks whether current test has had fatal error
Parameters
err Error param to check
Returns
true if test should abort, false else
Definition at line 144 of file tests.cpp.
Referenced by test_entity_data_array::run(), test_entity_spectrum::run(), and test_entity_levelone::run().
void tests::clean_test_outdir (bool no_clean) private
Clean the test directory
Removes contents and directory tests_tmp_dir, unless the no_clean parameter is set, when nothing is done. Note there may be other flags to consider so this is not as stupid as it seems. NB this writes to log file!
Parameters
no_clean If set, do nothing
Definition at line 43 of file tests.cpp.
Referenced by cleanup_tests().
void tests::cleanup_tests () private
Clean up after testing
Deletes test objects, and closes logfile
Definition at line 354 of file tests.cpp.
void tests::create_test_outdir () private
Create the test directory
Creates the directory tests_tmp_dir for temporary test output. If the directory exists, nothing is done and the no_clean flag is set
Definition at line 29 of file tests.cpp.
Referenced by setup_tests().
std::string tests::get_colour_escape (char col) inline private
This returns the terminal escape string to set given colour.
Available colour codes are RGB, CMYK and W(hite) plus * (bold) _ (underlined) ? (blink, irritating and not supported on some terminals) and $ (reverse foreground and background). A call with no arguments, or with 0 or '0' reset to default.
Parameters
col The colour code
Returns
String giving VT100 escape for colour
Definition at line 241 of file tests.cpp.
Referenced by set_colour().
std::string tests::get_printable_error (int err, int test_id) private
Make an error message
Converts error code to printable string, adds code for reference and adds test name. Note code is bitmask and additional errors are appended together
Parameters
err Error code
test_id Index of current test in list
Returns
Error information as printable string
Definition at line 199 of file tests.cpp.
Referenced by report_err().
bool tests::is_fatal (int err) private
Checks whether error is fatal
Parameters
err Error code, one of err_codes
Returns
Boolean true if fatal, false else
Definition at line 133 of file tests.cpp.
Referenced by check_for_abort(), and report_err().
void tests::report_err (int err, int test_id = -1)
Log error
Logs error text corresponding to code err for test defined by test_id.
Parameters
err Error to report
test_id Index of corresponding test
Definition at line 162 of file tests.cpp.
Referenced by run_tests().
void tests::report_info (std::string info, int verb_to_print = 1)
Other test info
Records string info to the tests.log file and to screen, according to requested verbosity.
Parameters
info Information to print
verb_to_print Verbosity level above which to print this info
Definition at line 184 of file tests.cpp.
Referenced by add_test(), test_entity_spectrum::albertGs_tests(), test_entity_plasma::analytic_dispersion(), test_entity_data_array::assign(), test_entity_data_array::basic_tests(), test_entity_levelone::basic_tests(), test_entity_d::basic_tests(), test_entity_spectrum::basic_tests1(), test_entity_spectrum::basic_tests2(), test_entity_bounce::bounce_cases(), clean_test_outdir(), cleanup_tests(), create_test_outdir(), test_entity_get_and_fft::fft_and_check_1d(), test_entity_d::full_D_tests(), test_entity_plasma::high_density(), test_entity_data_array::io_tests(), test_entity_get_and_fft::one_d(), test_entity_plasma::other_modes(), test_entity_plasma::phi_dom(), test_entity_d::read_padie_data(), test_entity_plasma::resonant_freq(), test_entity_plasma::resonant_freq_poly(), test_entity_reader::run(), test_entity_levelone::run(), test_entity_basic_maths::run(), test_entity_d::run(), test_entity_extern_maths::run(), test_entity_bounce::run(), test_entity_nonthermal::run(), test_entity_data_array::technical_tests(), test_entity_spectrum::technical_tests(), test_entity_nonthermal::test_lookup(), test_entity_data_array::three_d_and_shift(), and test_entity_get_and_fft::two_d().
bool tests::run_tests ()
Run scheduled tests
Runs each test in list and reports total errors found.
Returns
0 for no errors, 1 else
Definition at line 97 of file tests.cpp.
Referenced by main().
void tests::set_colour (char col = 0)
Set output text colour
Set terminal output colour using std escape sequences. NB technically not MPI safe. Use sparingly to highlight important information. Available colour codes are RGB, CMYK and W(hite) plus * (bold) _ (underlined) ? (blink, irritating and not supported on some terminals) and $ (reverse foreground and background). A call with no arguments, or with 0 or '0' reset to default.
Parameters
col Colour code, one of rgb cmyk or [w]hite, or format code,*_?$ 0, '0' or blank
Definition at line 232 of file tests.cpp.
Referenced by test_entity_data_array::basic_tests(), check_for_abort(), report_err(), and run_tests().
void tests::set_runtime_flags (int argc, char * argv[])
Set the runtime flags
Takes the command line args and stores in the runtime flags map. Each flag can be either a -thing or a -thing val where val is an int. Flags may not start with a digit
Parameters
argc Command line parameter number
argv Command line parameter list
Definition at line 65 of file tests.cpp.
Referenced by main().
bool tests::set_userdef_error (int err_code, std::string message)
Set a user-defined error string
Sets message associated with err_code to message string. NOTE this affects code associated with past and future use of the err_code string.
Parameters
err_code Code to set, one of the TEST_USERDEF_ERR[x]
message Message for this error
Returns
0 success, 1 for invalid change (trying to change a non-user error)
Definition at line 378 of file tests.cpp.
Referenced by setup_tests().
void tests::set_verbosity (size_t verb)
Set verbosity
Set the verbosity of testing output, from 0 (minimal) to max_verbos cap
Parameters
verb Verbosity level to set
Definition at line 56 of file tests.cpp.
Referenced by main(), and setup_tests().
void tests::setup_tests () private
Setup test bed
Opens reporting file, creates temporary dir. Then instantiates all the test objects and adds them into the test_list
Todo:
Clean up error codes
Todo:
Clean up printing verbosities
Definition at line 304 of file tests.cpp.
Member Data Documentation
int tests::current_test_id private
Number in list of test being run
Definition at line 99 of file tests.h.
Referenced by check_for_abort(), cleanup_tests(), report_err(), and run_tests().
bool tests::no_clean = false private
If true, do not clean up testing output directory
Definition at line 108 of file tests.h.
Referenced by cleanup_tests(), and create_test_outdir().
std::fstream* tests::outfile private
Output file handle
Definition at line 98 of file tests.h.
Referenced by cleanup_tests(), report_err(), report_info(), and setup_tests().
std::map<std::string, int> tests::runtime_flags
Strings for runtime control
Definition at line 111 of file tests.h.
Referenced by cleanup_tests(), test_entity_d::full_D_tests(), test_entity_levelone::run(), test_entity_d::run(), and set_runtime_flags().
std::vector<test_entity*> tests::test_list private
List of tests to run
Definition at line 100 of file tests.h.
Referenced by add_test(), check_for_abort(), cleanup_tests(), get_printable_error(), and run_tests().
int tests::verbosity private
Verbosity level of output
Definition at line 101 of file tests.h.
Referenced by report_info(), and set_verbosity().
The documentation for this class was generated from the following files:
include/tests.h
src/tests.cpp