WIPPS: test_entity_get_and_fft Class Reference
test_entity_get_and_fft Class Reference
Test code » Basic tests
#include <tests_basic_and_code.h>
Public Member Functions
test_entity_get_and_fft ()
virtual ~test_entity_get_and_fft ()
virtual int run ()
Private Member Functions
int one_d ()
int two_d ()
int fft_and_check_1d (data_array &dat_in, data_array &dat_fft, my_type expected_max, bool single_max=false)
Private Attributes
reader * test_rdr
Additional Inherited Members
Public Attributes inherited from test_entity
std::string name
Detailed Description
Combined test: reads test sdf file, stores into data array and runs fft. Test data should be a sine curve with one major frequency which is then checked
Definition at line 66 of file tests_basic_and_code.h.
Constructor & Destructor Documentation
test_entity_get_and_fft::test_entity_get_and_fft ()
Setup FFT testing
Definition at line 609 of file tests_basic_and_code.cpp.
test_entity_get_and_fft::~test_entity_get_and_fft () virtual
Teardown FFT testing
Definition at line 614 of file tests_basic_and_code.cpp.
Member Function Documentation
int test_entity_get_and_fft::fft_and_check_1d (data_array & dat_in, data_array & dat_fft, my_type expected_max, bool single_max = false) private
Check 1-d FFT frequencies
FFTS data_in into data_fft and then hunts for 1 or two maxima, depending on n_maxima, and checks they're at axis values of ± expected_max
Parameters
dat_in Input array
dat_fft FFT'd data array
expected_max Expected peak axis value
single_max Whether data has a single maximum freq (e.g. at 0)
Returns
Error code
Definition at line 700 of file tests_basic_and_code.cpp.
Referenced by one_d().
int test_entity_get_and_fft::one_d () private
Checks fft in 1-d
Read, fft and check for 1-d data
Returns
Error code
Definition at line 644 of file tests_basic_and_code.cpp.
Referenced by run().
int test_entity_get_and_fft::run () virtual
Run the test. Pure virtual means this must be defined in any concrete class
Returns
Error code from test, one of err_codes
Checks full read and fft procedure
Reads a test sdf file, stores into data array and runs fft. Test data should be a sine curve with one major frequency which is then checked. Note frequency is hard coded to match that produced by sin.deck
Returns
Error code
Implements test_entity.
Definition at line 619 of file tests_basic_and_code.cpp.
int test_entity_get_and_fft::two_d () private
Check 2-d FFT frequencies
FFTS data_in into data_fft and then hunts for maxima, and checks against hard coded expected values
Returns
Error code
Definition at line 758 of file tests_basic_and_code.cpp.
Referenced by run().
Member Data Documentation
reader* test_entity_get_and_fft::test_rdr private
File reader for testing
Definition at line 68 of file tests_basic_and_code.h.
Referenced by one_d(), run(), two_d(), and ~test_entity_get_and_fft().
The documentation for this class was generated from the following files:
include/tests_basic_and_code.h
src/tests_basic_and_code.cpp