WIPPS: test_entity_plasma Class Reference
test_entity_plasma Class Reference
Test code » Calculation tests
#include <tests_data_and_calc.h>
Public Member Functions
test_entity_plasma ()
virtual ~test_entity_plasma ()
virtual int run ()
Private Member Functions
int resonant_freq ()
int resonant_freq_poly ()
int high_density ()
int other_modes ()
int phi_dom ()
int analytic_dispersion ()
Private Attributes
plasma * plas
Additional Inherited Members
Public Attributes inherited from test_entity
std::string name
Detailed Description
Check plasma functions, get_omega and dispersion relation
Definition at line 36 of file tests_data_and_calc.h.
Constructor & Destructor Documentation
test_entity_plasma::test_entity_plasma ()
Setup tests for plasma
Create plasma object from file
Definition at line 29 of file tests_data_and_calc.cpp.
test_entity_plasma::~test_entity_plasma () virtual
Teardown plasma tests
Definition at line 42 of file tests_data_and_calc.cpp.
Member Function Documentation
int test_entity_plasma::analytic_dispersion () private
Check analytic dispersion relations
Checks the analytic relations, both ways and including derivatives
Returns
Error code
Definition at line 72 of file tests_data_and_calc.cpp.
Referenced by run().
int test_entity_plasma::high_density () private
Tests high density approximation for dispersion relations
Test if the mu found by get_root and get_phi_mu_om matches the high density whistler in high dens regime
Returns
Error code
my_mu.mu should roughly equal Stix 2.45
my_mu_dens should EXACTLY equal Stix 2.45 without the 1.0 term
Definition at line 445 of file tests_data_and_calc.cpp.
Referenced by run().
int test_entity_plasma::other_modes () private
Test dispersion solver further
Tests dispersion solver for other wave modes, O and X
Returns
Error code
Definition at line 510 of file tests_data_and_calc.cpp.
Referenced by run().
int test_entity_plasma::phi_dom () private
Test other plasma returns
Checks the values of mu.dom, mu.dmudtheta and phi against special cases.
Returns
Error code
Approx numerical derivative
Approx numerical derivative. Manually fix signs
Definition at line 560 of file tests_data_and_calc.cpp.
Referenced by run().
int test_entity_plasma::resonant_freq () private
Check resonant frequency solver
Checks the returned resonant frequency obeys equations used to derive it by solving both for mu.
Returns
Error code
Now check each element of the resonant frequency solution set satisfies Stix 2.45 and the resonance condition together
Definition at line 238 of file tests_data_and_calc.cpp.
Referenced by run().
int test_entity_plasma::resonant_freq_poly () private
Check resonant frequency solver
Checks the returned resonant frequencies from the high-density and full polynomials have full solutions and match to reasonable degree
Returns
Error code
Definition at line 328 of file tests_data_and_calc.cpp.
Referenced by run().
int test_entity_plasma::run () virtual
Run the test. Pure virtual means this must be defined in any concrete class
Returns
Error code from test, one of err_codes
Test resonant frequencies and refractive indices
Checks the resonant frequencies obey the equations used to derive them. Checks the dispersion roots for Whistlers match those found using high-density approx. Checks plasma O and X mode dispersion too. Note, first call for issues with these tests is to check returned mu.err on failing tests
Returns
Error code
Implements test_entity.
Definition at line 47 of file tests_data_and_calc.cpp.
Member Data Documentation
plasma* test_entity_plasma::plas private
Pointer to plasma object under test
Definition at line 38 of file tests_data_and_calc.h.
Referenced by analytic_dispersion(), high_density(), other_modes(), phi_dom(), resonant_freq(), resonant_freq_poly(), run(), test_entity_plasma(), and ~test_entity_plasma().
The documentation for this class was generated from the following files:
include/tests_data_and_calc.h
src/tests_data_and_calc.cpp