WIPPS: test_entity_data_array Class Reference
test_entity_data_array Class Reference
Test code » Basic tests
#include <tests_basic_and_code.h>
Public Member Functions
test_entity_data_array ()
virtual int run ()
Private Member Functions
int technical_tests ()
int basic_tests ()
int assign ()
int three_d_and_shift ()
int io_tests ()
int set_vals_2d (data_array &array)
int set_vals_2d_and_sum (data_array &array, my_type &total)
int set_vals_3d (data_array &array)
Additional Inherited Members
Public Attributes inherited from test_entity
std::string name
Detailed Description
Test for data array class, assigns values to entry and reads back
Definition at line 47 of file tests_basic_and_code.h.
Constructor & Destructor Documentation
test_entity_data_array::test_entity_data_array ()
Setup data array test
Definition at line 111 of file tests_basic_and_code.cpp.
Member Function Documentation
int test_entity_data_array::assign () private
Check basic assignments
Set values and check basic assignment worked
Returns
Error code
Definition at line 265 of file tests_basic_and_code.cpp.
Referenced by run().
int test_entity_data_array::basic_tests () private
test basic array functions
Test maxval, total etc etc, resizer, maths
Returns
Error code
Definition at line 293 of file tests_basic_and_code.cpp.
Referenced by run().
int test_entity_data_array::io_tests () private
Check read/write
Check data_array write to file and then read
Returns
Error code
Definition at line 568 of file tests_basic_and_code.cpp.
Referenced by run().
int test_entity_data_array::run () virtual
Run the test. Pure virtual means this must be defined in any concrete class
Returns
Error code from test, one of err_codes
Test data arrays
Puts data into selected elements of a data array and reads back. Checks indexing, and bounds.
Returns
Error code
Implements test_entity.
Definition at line 175 of file tests_basic_and_code.cpp.
int test_entity_data_array::set_vals_2d (data_array & array) private
Create 2-d test array
Assign each element of test_array and its axis elements to varying values.
Parameters
array The array to assign. Should be 2-d of any size
Returns
Error code
Definition at line 225 of file tests_basic_and_code.cpp.
Referenced by assign(), basic_tests(), io_tests(), and technical_tests().
int test_entity_data_array::set_vals_2d_and_sum (data_array & array, my_type & total) private
Create 2-d test array
Assign each element of test_array and its axis elements to varying values.
Parameters
array The array to assign
[out] total Sum of values assigned
Returns
Error code
Definition at line 196 of file tests_basic_and_code.cpp.
Referenced by basic_tests(), and set_vals_2d().
int test_entity_data_array::set_vals_3d (data_array & array) private
Create 3-d test array
Assign each element of test_array and its axis elements to varying values.
Parameters
array The array to assign. Should be 3-d of any size
Returns
Error code
Definition at line 236 of file tests_basic_and_code.cpp.
Referenced by three_d_and_shift().
int test_entity_data_array::technical_tests () private
Technical testing
Check things like copy constructors
Returns
Error code
Definition at line 519 of file tests_basic_and_code.cpp.
Referenced by run().
int test_entity_data_array::three_d_and_shift () private
Test 3-d resizer and shift
Tests resize in 3-d and shift in 3-d. If latter works, it should work in 2 or 1-d definitely.
Returns
Error code
Definition at line 449 of file tests_basic_and_code.cpp.
Referenced by run().
The documentation for this class was generated from the following files:
include/tests_basic_and_code.h
src/tests_basic_and_code.cpp